[package]
version = "0.1.0"
edition = "2024"
name = "ttf-view"
description = "A TrueType/OpenType font parsing/viewing library and a CLI tool."
authors = ["Chasmical <kaz@chsm.dev>"]
keywords = []
categories = []
repository = "https://github.com/Chasmical/ttf-view"
license = "MIT OR Apache-2.0"
readme = "../../README.md"

[dependencies]
